server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/social_d"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org.springframework.security: DEBUG

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 4 # in hour

app:
  services:
    profile: http://localhost:8081/profile