server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/social_d"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org.springframework.security: DEBUG

jwt:
  signer-key: "bzJqFprhA2iBjU1Nt4T+JAFNQWTik8PTp8acU7EeuOoSvvxq3eBHOywKUpWfHdpt"
  one-day: 24 # hour
  valid-duration: 24 # hour
