server:
  port: 8081
  servlet:
    context-path: /social-network/api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/social_network"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signer-key: "bzJqFprhA2iBjU1Nt4T+JAFNQWTik8PTp8acU7EeuOoSvvxq3eBHOywKUpWfHdpt"